// ==========================================================
// NODE.JS PROCESS MODULE
// LESSON 07 — PROCESS SIGNALS
// ==========================================================
//
// Purpose:
// Learn how a Node.js process responds to operating-system
// signals.
//
// ==========================================================

// ==========================================================
// 1. HANDLE SIGINT
// ==========================================================
//
// SIGINT is normally generated by:
//
// Ctrl + C
//
// ==========================================================

process.on("SIGINT", () => {
  console.log("\n========================================");

  console.log(" SIGINT RECEIVED ");

  console.log("========================================");

  console.log("Shutting down Node.js process...");
  process.exit(0);
});

// ==========================================================
// 2. KEEP PROCESS RUNNING
// ==========================================================

setInterval(() => {
  console.log("Process is running...");
}, 2000);
